# Generated by Django 4.0 on 2022-08-29 03:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2),
        ),
    ]
